#Create the network previusly
# docker network create --gateway 172.16.1.1 --subnet 172.16.1.0/24 kaibacorp
version: "3"
services:
  kaibacorp.php.playground:
    stdin_open: true
    tty: true
    build: .
    image: kaibacorp.php72.playground
    container_name: kaibacorp.php72.playground
    volumes:
      - "./src/:/usr/share/nginx/html"
    ports:
      - "80:80"
    networks:
      kaibacorp:
        ipv4_address: 172.16.1.3
networks:
  kaibacorp:
    external: true